postgres:
  host: "localhost"
  port: "5432"
  username: "musicman"
  password: "musicman"
  database: "musicman"
  app_name: "musicman"
  max_conns: 3

minio:
  endpoint: "localhost:9000"
  access_key: "minioadmin"
  secret_key: "minioadmin"
  use_ssl: false
  bucket_name: "musicman"
  max_retries: 5

http:
  addr: ":8080"

yookassa:
  host: "https://api.yookassa.ru"
  secret_key: ""
  account_id: ""